# SonarCloud
# Análisis de código fuente con SonarCloud

trigger: none # Disable CI triggers.
#- master

resources:
- repo: self

variables:
# a regular variable
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: 'latest'
- name: vmImageName
  value: 'ubuntu-latest'
# a variable group
- group: Mis_Variables_LAB4


stages:
  - stage: CodeSecurityScan
    displayName: Code Security Analysis
    jobs:
      - job: SonarCloud
        displayName: SonarCloud
        pool:
          vmImage: $(vmImageName)
        steps:
        - checkout: self
          fetchDepth: 0
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'Connection SonarCloud LAB4'
            organization: 'Ramiramc'
            scannerMode: 'CLI'
            configMode: 'manual'
            cliProjectKey: 'Ramiramc_reactjs-shopping-cart-lab4'
            cliProjectName: 'reactjs-shopping-cart-lab4'
            cliSources: '.'
        - task: SonarCloudAnalyze@1
        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'