# Trivy
# Análisis profundo de un contenedor con la herramienta de Trivy
# 

trigger: none # Disable CI triggers.
#- master

resources:
- repo: self

variables:
# a regular variable
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: 'latest'
- name: vmImageName
  value: 'ubuntu-latest'
- name: sariflog
  value: 'ImageAnalysisLogs'
# a variable group
- group: Mis_Variables_LAB4

stages:
  - stage: SecurityScan
    displayName: SecurityAnalysis
    jobs:
      - job: Trivy
        displayName: Trivy
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: $(ACR_Conn)
            command: 'login'

        - task: trivy@1
          inputs:
            version: 'latest'
            debug: true
            loginDockerConfig: true
            image: '$(ACR_NAME)/$(WEBAPP_NAME):latest'
            exitCode: '0'
 