# SNYK
# Con este flujo se desea realizar el análisis de una aplicación contenerizada con Snyk

trigger: none # Disable CI triggers.
#- master

resources:
- repo: self

variables:
# a regular variable
- name: dockerfilePath
  value: '$(Build.SourcesDirectory)/Dockerfile'
- name: tag
  value: 'latest'
- name: vmImageName
  value: 'ubuntu-latest'
# a variable group
- group: Mis_Variables_LAB4


stages:
  - stage: SecurityScan
    displayName: SecurityAnalysis
    jobs:
      - job: Snyk
        displayName: Snyk
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: $(ACR_Conn)
            command: 'login'
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: $(Snyk_Conn)
            testType: 'container'
            dockerImageName: $(ACR_NAME)/$(WEBAPP_NAME):latest
            dockerfilePath: '$(dockerfilePath)'
            monitorWhen: 'always'
            failOnIssues: false